version: '3.8'
services:
  textswapauthapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;http://+:5000
      - ConnectionStrings__PostgreSQL=Host=db;Port=5432;Database=AuthDB;Username=postgres;Password=Mod12345
      - Redis__Host=redis
    depends_on:
      - "db"
    ports:
      - "5000"
      - "5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro 
  db:
    image: postgres:latest
    restart: always
    container_name: textswapauthapi.db
    environment:
        - POSTGRES_BD=AuthDB
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=Mod12345
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
        - 5432:5432
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
   
        
       
volumes:
  pgdata: